config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
  resources :tweets
  resources :users
  get "/users/:id/likes", to: "users#show_likes", as: :show_user_likes

  get "/login", to: "sessions#new", as: :login_path
  post "/login", to: "sessions#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  # Associations
  belongs_to :user, counter_cache: true
  belongs_to :tweet, counter_cache: true
  # Validations
  validates :user_id, uniqueness: {
    scope: :tweet_id,
    message: "should be a unique combination"
  }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Associations between models
  belongs_to :user, counter_cache: true
  has_many :likes, dependent: :destroy
  # Relation Self.Join
  has_many :replies, class_name: "Tweet",
                     foreign_key: "replied_to_id",
                     dependent: :destroy,
                     inverse_of: "replied_to"
  belongs_to :replied_to, class_name: "Tweet", optional: true, counter_cache: :replies_count

  # Validations
  validates :body, presence: true, length: { maximum: 140 }
  validate :tweet_replied_to

  # Query interface
  enum :category, {
    post: 0,
    answer: 1
  }
  # Callbacks
  before_validation :set_upload_date, on: :create
  after_save :set_update_tweet

  private

  def tweet_replied_to
    if category == "answer" && Tweet.find_by(id: replied_to_id).nil?
      errors.add(:replied_to_id, "should be a valid post tweet")
    elsif category == "post" && replied_to_id
      errors.add(:replied_to_id, "should be nil")
    end
  end

  def set_upload_date
    self.upload_date ||= Time.current if new_record? || upload_date.blank?
    self.update_tweet = self.upload_date
  end

  def set_update_tweet
    return unless saved_change_to_body?

    self.update_tweet = Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #  :recoverable, :rememberable, :validatable
  # Authentication
  has_secure_password
  # Associations between models
  has_many :likes, dependent: :destroy
  has_many :tweets, dependent: :destroy
  # Query Interface
  enum :role, {
    member: 0,
    admin: 1
  }
  # Validations
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password_digest, presence: true, length: { minimum: 6 }, format: { without: /\s/ }
  validates :username, presence: true, uniqueness: true,
                       length: { minimum: 3, maximum: 16 },
                       format: { without: /\s/ }

  validates :name, presence: true

  # # Actives Storage
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user

  # def logged_in?
  #   false
  # end

  # def authenticate_user
  #   flash[:message]

  #   return if logged_in?

  #   flash[:message] = "You need to be loggued in to continue"
  #   redirect_to login_path
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :authenticate_user
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      redirect_to user_path(user)
    else
      flash.now[:message] = "Invalid credentials"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.where(category: "post").order(upload_date: :desc)
  end

  def show
    @tweet = Tweet.find_by(id: params[:id])
  end

  def new; end
  def edit; end

  def update; end

  def destroy; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to tweets_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.authenticate(user_params[:password]).present? && user_params[:password] == user_params[:password_confirmation]
      @user.update(
        name: user_params[:name],
        username: user_params[:username],
        email: user_params[:email],
        password: user_params[:new_password]
      )
      redirect_to user_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy; end

  def show_likes
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :name, :password, :password_confirmation,
                                 :avatar, :new_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_ago_in_words(from_time, options = {})
    time_ago = distance_of_time_in_words(Time.zone.now, from_time, options)

    number, unit = time_ago.match(/(\d+) (\w+)/).captures

    number = "1" if number == "about"

    "#{number} #{unit}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_tweet_block.html.erb
<%= link_to tweet_path(tweet), class: "tweet-block-link" do %>
  <div class="tweet-block">
    <div class="tweet-block__avatar">
      <%= image_tag(tweet.user.avatar, alt: "avatar_user", class: "tweet-block__avatar-image") %>
    </div>
    <div class="tweet-block__tweet-details">
      <div class="tweet-block__user-details">
        <span class="tweet-block__user-name"><%= tweet.user.name %></span>
        <span class="tweet-block__user-username"><%= "@" + tweet.user.username %></span>
      </div>
      <span class="tweet-block__tweet-update"><%= time_ago_in_words("#{tweet.update_tweet}") + " ago" %></span>
    </div>
    <div class="tweet-block__body-user-tweet">
      <p>
        <%= tweet.body %>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quia molestiae minus corporis odio, illum
        fugiat animi nihil natus praesentium est amet unde officiis velit similique quam sunt! Numquam, eaque!.Lorem
        ipsum dolor sit amet consectetur adipisicing elit. Adipisci quia molestiae minus corporis odio, illum fugiat
        animi nihil natus praesentium est amet unde officiis velit similique quam sunt! Numquam, eaque!
      </p>
    </div>
    <div class="tweet-block__actions-tweet">
      <div class="tweet-block__actions-self-user">
        <div class="tweet-block__tweets">
          <i class="material-symbols-outlined">edit_note</i>
        </div>
        <div class="tweet-block__likes">
          <i class="material-symbols-outlined">delete</i>
        </div>
      </div>
      <div class="tweet-block__actions-user">
        <div class="tweet-block__tweets">
          <i class="material-symbols-outlined">chat</i>
        </div>
        <div class="tweet-block__tweets"><%= tweet.replies_count %></div>
        <div class="tweet-block__likes">
          <i class="material-symbols-outlined">favorite</i>
        </div>
        <div class="tweet-block__likes"><%= tweet.likes_count %></div>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/index.html.erb
<h1>Tweets</h1>
<div>
  <% @tweets.each do |tweet| %>
    <%= render partial: "shared/tweet_block", locals: {tweet: tweet} %>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

app/views/tweets/show.html.erb
<h2>Tweet Detail</h2>
<%= render partial: "shared/tweet_block", locals: {tweet: @tweet} %>
<div>
  <h3>Retweets</h3>
</div>
<div>
  <% @tweet.replies.each do |answer| %>
    <%= render partial: "shared/tweet_block", locals: {tweet: answer} %>
  <% end %>
</div>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_with model: user  do |form| %>
  <% input_labels=[[1,"username","example"],[1,"email","example@mail.com"],[1,"name","Example Name"],[2,"password","*"*8],[2,"password_confirmation","*"*8]] %>
  <div class="user-form__container">
    <% input_labels.each do |input_label| %>
      <%= form.label input_label[1].to_sym, input_label[1].capitalize, class: "user-form__label block" %>
      <% if input_label[0]==1 %>
        <%= form.text_field input_label[1].to_sym, class: "user-form__input block", placeholder: input_label[2] %>
      <% else %>
        <%= form.password_field input_label[1].to_sym, class: "user-form__input block", placeholder: input_label[2] %>
      <% end %>
      <% if user.errors.messages[input_label[1].to_sym].any? %>
        <span class="user-form__error-messages block">
          <%= user.errors.messages[input_label[1].to_sym].join(", ")%>
        </span>
      <% end %>
    <% end %>
    <% if  !current_page?(new_user_path)%>
      <%= form.label :new_password, "New Password", class: "user-form__label block" %>
      <%= form.password_field :new_password, class: "user-form__input block" %>
    <% end %>
    <%= form.label :avatar, "Avatar", class: "user-form__label block" %>
    <%= form.file_field :avatar, class: "user-form__atached", accept: "image/png, image/jpeg" %>
    <%= form.submit status_button, class:"button-account button-pink flex jc-c"%>
  </div>
<% end %>

app/views/users/_profile.html.erb
<div class="profile-block">
  <% if user.avatar.attached? %>
    <%= image_tag(user.avatar, alt: "avatar_user_profile", class: "profile-block__avatar-image") %>
  <% end %>
  <span class="content_tipic text_n"><%= user.name %></span>
  <span class="content_tipic">@<%= user.username %></span>
  <p class="content_tipic">Joined on <%= user.created_at.strftime('%B %e, %Y')
 %>
  </p>
  <%= link_to edit_user_path(user), class: "button" do %>
    Edit Profile
  <% end %>
  <% if  current_page?(user_path)%>
    <% name_class_like="activity_user-link activity_user-link-deactivated" %>
    <% name_class_tweet="activity_user-link activity_user-link-active" %>
  <% elsif  current_page?(show_user_likes_path(user)) %>
    <% name_class_like="activity_user-link activity_user-link-active" %>
    <% name_class_tweet="activity_user-link activity_user-link-deactivated" %>
  <% end %>
  <div class="activity_user">
    <%= link_to user_path, class: name_class_tweet do%>
      Tweets (<%= user.tweets_count%>)
    <% end %>
    <%= link_to show_user_likes_path(user), class: name_class_like do%>
      Likes (<%= user.likes_count%>)
    <% end %>
  </div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h2 class="form-title full_center _0">Edit Profile</h2>
<div class="user-form">
  <%= render partial: "form", locals: {user: @user,status_button: "update"} %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h2 class="form-title full_center _0">Create an account</h2>
<div class="user-form">
  <div class="user-form__container">
    <span class="container-simple block full_center _0">CONTINUE</span>
    <%= link_to 'GitHub', "/", class: "button-account button-black flex jc-c" %>
    <span class="container-simple block full_center _0">OR</span>
  </div>
  <%= render partial: "form", locals: {user: @user,status_button: "sign up"} %>
</div>

app/views/users/show.html.erb
<h2>Profile</h2>
<%= render partial: "profile", locals: {user: @user} %>
<div>
  <% @user.tweets.each do |answer| %>
    <%= render partial: "shared/tweet_block", locals: {tweet: answer} %>
  <% end %>
</div>

app/views/users/show_likes.html.erb
<h2>Profile</h2>
<%= render partial: "profile", locals: {user: @user} %>
<div>
  <% @user.likes.each do |answer| %>
    <%= render partial: "shared/tweet_block", locals: {tweet: answer.tweet} %>
  <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>